# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = ./

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = ./

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"KPHP\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/isharipov/CODE/kphp-timelib/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isharipov/CODE/kphp-timelib/CMakeFiles /home/isharipov/CODE/kphp-timelib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isharipov/CODE/kphp-timelib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kphp-timelib-includecopy

# Build rule for target.
kphp-timelib-includecopy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kphp-timelib-includecopy
.PHONY : kphp-timelib-includecopy

# fast build rule for target.
kphp-timelib-includecopy/fast:
	$(MAKE) -f CMakeFiles/kphp-timelib-includecopy.dir/build.make CMakeFiles/kphp-timelib-includecopy.dir/build
.PHONY : kphp-timelib-includecopy/fast

#=============================================================================
# Target rules for targets named kphp-timelib-codegen

# Build rule for target.
kphp-timelib-codegen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kphp-timelib-codegen
.PHONY : kphp-timelib-codegen

# fast build rule for target.
kphp-timelib-codegen/fast:
	$(MAKE) -f CMakeFiles/kphp-timelib-codegen.dir/build.make CMakeFiles/kphp-timelib-codegen.dir/build
.PHONY : kphp-timelib-codegen/fast

#=============================================================================
# Target rules for targets named kphp-timelib

# Build rule for target.
kphp-timelib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kphp-timelib
.PHONY : kphp-timelib

# fast build rule for target.
kphp-timelib/fast:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/build
.PHONY : kphp-timelib/fast

astro.o: astro.c.o

.PHONY : astro.o

# target to build an object file
astro.c.o:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/astro.c.o
.PHONY : astro.c.o

astro.i: astro.c.i

.PHONY : astro.i

# target to preprocess a source file
astro.c.i:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/astro.c.i
.PHONY : astro.c.i

astro.s: astro.c.s

.PHONY : astro.s

# target to generate assembly for a file
astro.c.s:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/astro.c.s
.PHONY : astro.c.s

dow.o: dow.c.o

.PHONY : dow.o

# target to build an object file
dow.c.o:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/dow.c.o
.PHONY : dow.c.o

dow.i: dow.c.i

.PHONY : dow.i

# target to preprocess a source file
dow.c.i:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/dow.c.i
.PHONY : dow.c.i

dow.s: dow.c.s

.PHONY : dow.s

# target to generate assembly for a file
dow.c.s:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/dow.c.s
.PHONY : dow.c.s

interval.o: interval.c.o

.PHONY : interval.o

# target to build an object file
interval.c.o:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/interval.c.o
.PHONY : interval.c.o

interval.i: interval.c.i

.PHONY : interval.i

# target to preprocess a source file
interval.c.i:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/interval.c.i
.PHONY : interval.c.i

interval.s: interval.c.s

.PHONY : interval.s

# target to generate assembly for a file
interval.c.s:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/interval.c.s
.PHONY : interval.c.s

parse_date.o: parse_date.c.o

.PHONY : parse_date.o

# target to build an object file
parse_date.c.o:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_date.c.o
.PHONY : parse_date.c.o

parse_date.i: parse_date.c.i

.PHONY : parse_date.i

# target to preprocess a source file
parse_date.c.i:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_date.c.i
.PHONY : parse_date.c.i

parse_date.s: parse_date.c.s

.PHONY : parse_date.s

# target to generate assembly for a file
parse_date.c.s:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_date.c.s
.PHONY : parse_date.c.s

parse_iso_intervals.o: parse_iso_intervals.c.o

.PHONY : parse_iso_intervals.o

# target to build an object file
parse_iso_intervals.c.o:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_iso_intervals.c.o
.PHONY : parse_iso_intervals.c.o

parse_iso_intervals.i: parse_iso_intervals.c.i

.PHONY : parse_iso_intervals.i

# target to preprocess a source file
parse_iso_intervals.c.i:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_iso_intervals.c.i
.PHONY : parse_iso_intervals.c.i

parse_iso_intervals.s: parse_iso_intervals.c.s

.PHONY : parse_iso_intervals.s

# target to generate assembly for a file
parse_iso_intervals.c.s:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_iso_intervals.c.s
.PHONY : parse_iso_intervals.c.s

parse_tz.o: parse_tz.c.o

.PHONY : parse_tz.o

# target to build an object file
parse_tz.c.o:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_tz.c.o
.PHONY : parse_tz.c.o

parse_tz.i: parse_tz.c.i

.PHONY : parse_tz.i

# target to preprocess a source file
parse_tz.c.i:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_tz.c.i
.PHONY : parse_tz.c.i

parse_tz.s: parse_tz.c.s

.PHONY : parse_tz.s

# target to generate assembly for a file
parse_tz.c.s:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_tz.c.s
.PHONY : parse_tz.c.s

parse_zoneinfo.o: parse_zoneinfo.c.o

.PHONY : parse_zoneinfo.o

# target to build an object file
parse_zoneinfo.c.o:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_zoneinfo.c.o
.PHONY : parse_zoneinfo.c.o

parse_zoneinfo.i: parse_zoneinfo.c.i

.PHONY : parse_zoneinfo.i

# target to preprocess a source file
parse_zoneinfo.c.i:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_zoneinfo.c.i
.PHONY : parse_zoneinfo.c.i

parse_zoneinfo.s: parse_zoneinfo.c.s

.PHONY : parse_zoneinfo.s

# target to generate assembly for a file
parse_zoneinfo.c.s:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/parse_zoneinfo.c.s
.PHONY : parse_zoneinfo.c.s

timelib.o: timelib.c.o

.PHONY : timelib.o

# target to build an object file
timelib.c.o:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/timelib.c.o
.PHONY : timelib.c.o

timelib.i: timelib.c.i

.PHONY : timelib.i

# target to preprocess a source file
timelib.c.i:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/timelib.c.i
.PHONY : timelib.c.i

timelib.s: timelib.c.s

.PHONY : timelib.s

# target to generate assembly for a file
timelib.c.s:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/timelib.c.s
.PHONY : timelib.c.s

tm2unixtime.o: tm2unixtime.c.o

.PHONY : tm2unixtime.o

# target to build an object file
tm2unixtime.c.o:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/tm2unixtime.c.o
.PHONY : tm2unixtime.c.o

tm2unixtime.i: tm2unixtime.c.i

.PHONY : tm2unixtime.i

# target to preprocess a source file
tm2unixtime.c.i:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/tm2unixtime.c.i
.PHONY : tm2unixtime.c.i

tm2unixtime.s: tm2unixtime.c.s

.PHONY : tm2unixtime.s

# target to generate assembly for a file
tm2unixtime.c.s:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/tm2unixtime.c.s
.PHONY : tm2unixtime.c.s

unixtime2tm.o: unixtime2tm.c.o

.PHONY : unixtime2tm.o

# target to build an object file
unixtime2tm.c.o:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/unixtime2tm.c.o
.PHONY : unixtime2tm.c.o

unixtime2tm.i: unixtime2tm.c.i

.PHONY : unixtime2tm.i

# target to preprocess a source file
unixtime2tm.c.i:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/unixtime2tm.c.i
.PHONY : unixtime2tm.c.i

unixtime2tm.s: unixtime2tm.c.s

.PHONY : unixtime2tm.s

# target to generate assembly for a file
unixtime2tm.c.s:
	$(MAKE) -f CMakeFiles/kphp-timelib.dir/build.make CMakeFiles/kphp-timelib.dir/unixtime2tm.c.s
.PHONY : unixtime2tm.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... kphp-timelib-includecopy"
	@echo "... kphp-timelib-codegen"
	@echo "... kphp-timelib"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... astro.o"
	@echo "... astro.i"
	@echo "... astro.s"
	@echo "... dow.o"
	@echo "... dow.i"
	@echo "... dow.s"
	@echo "... interval.o"
	@echo "... interval.i"
	@echo "... interval.s"
	@echo "... parse_date.o"
	@echo "... parse_date.i"
	@echo "... parse_date.s"
	@echo "... parse_iso_intervals.o"
	@echo "... parse_iso_intervals.i"
	@echo "... parse_iso_intervals.s"
	@echo "... parse_tz.o"
	@echo "... parse_tz.i"
	@echo "... parse_tz.s"
	@echo "... parse_zoneinfo.o"
	@echo "... parse_zoneinfo.i"
	@echo "... parse_zoneinfo.s"
	@echo "... timelib.o"
	@echo "... timelib.i"
	@echo "... timelib.s"
	@echo "... tm2unixtime.o"
	@echo "... tm2unixtime.i"
	@echo "... tm2unixtime.s"
	@echo "... unixtime2tm.o"
	@echo "... unixtime2tm.i"
	@echo "... unixtime2tm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

